# Generated by Django 6.0.3 on 2026-04-07 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64, unique=True)),
                ('client_secret', models.CharField(blank=True, max_length=64)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('redirect_uris', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mcp_oauth_client',
            },
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('code_challenge', models.CharField(blank=True, max_length=128)),
                ('code_challenge_method', models.CharField(blank=True, default='S256', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcp.oauthclient')),
            ],
            options={
                'db_table': 'mcp_oauth_authorization_code',
                'indexes': [models.Index(fields=['code'], name='mcp_oauth_a_code_e51f8f_idx')],
            },
        ),
    ]
