# Generated by Django 6.0.3 on 2026-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_default_branch',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo',
            field=models.CharField(blank=True, help_text='GitHub repo in owner/repo format, e.g. acme/my-service', max_length=200),
        ),
    ]
