# Generated by Django 6.0.3 on 2026-04-05 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('webhook', 'GitHub Webhook'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('files_total', models.IntegerField(default=0)),
                ('files_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by_commit', models.CharField(blank=True, help_text='Git commit SHA', max_length=40)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Ingestion Job',
                'verbose_name_plural': 'Ingestion Jobs',
                'db_table': 'intelligence_ingestion_job',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('effort_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('answer', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('context_files', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Query Log',
                'verbose_name_plural': 'Query Logs',
                'db_table': 'intelligence_query_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndexedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Relative path within the project', max_length=500)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of file content', max_length=64)),
                ('last_indexed', models.DateTimeField()),
                ('functions_count', models.IntegerField(default=0)),
                ('classes_count', models.IntegerField(default=0)),
                ('endpoints_count', models.IntegerField(default=0)),
                ('signals_count', models.IntegerField(default=0)),
                ('crons_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexed_files', to='projects.project')),
            ],
            options={
                'verbose_name': 'Indexed File',
                'verbose_name_plural': 'Indexed Files',
                'db_table': 'intelligence_indexed_file',
                'ordering': ['file_path'],
                'unique_together': {('project', 'file_path')},
            },
        ),
    ]
