# Generated by Django 6.0.3 on 2026-04-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='Rolling LLM-generated summary of codebase insights from queries and ingestions')),
                ('queries_since_update', models.IntegerField(default=0, help_text='Number of queries logged since the last memory update')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Memory',
                'verbose_name_plural': 'Project Memories',
                'db_table': 'intelligence_project_memory',
            },
        ),
    ]
