# Generated by Django 6.0.3 on 2026-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_add_project_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedfile',
            name='content',
            field=models.TextField(blank=True, help_text='Full source code of the file'),
        ),
    ]
