# Generated by Django 6.0.3 on 2026-04-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_add_file_content'),
        ('projects', '0002_add_github_repo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('entity_type', models.CharField(choices=[('function', 'Function'), ('class', 'Class'), ('endpoint', 'Endpoint'), ('model', 'Django Model'), ('file', 'File')], max_length=20)),
                ('entity_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_descriptions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Entity Description',
                'verbose_name_plural': 'Entity Descriptions',
                'db_table': 'intelligence_entity_description',
                'indexes': [models.Index(fields=['project', 'entity_type'], name='intelligenc_project_70fcaf_idx'), models.Index(fields=['project', 'entity_name'], name='intelligenc_project_616513_idx')],
                'unique_together': {('project', 'file_path', 'entity_type', 'entity_name')},
            },
        ),
    ]
